services:
  zookeeper:
    image: zookeeper:3.8
    container_name: stormcrawler-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  nimbus:
    image: storm:2.8.2
    container_name: stormcrawler-nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    ports:
      - "6627:6627"
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper
    volumes:
      - ./storm.yaml:/conf/storm.yaml

  supervisor:
    image: storm:2.8.2
    container_name: stormcrawler-supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper
    volumes:
      - ./storm.yaml:/conf/storm.yaml

  ui:
    image: storm:2.8.2
    container_name: stormcrawler-ui
    command: storm ui
    depends_on:
      - nimbus
    ports:
      - "8080:8080"
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper
    volumes:
      - ./storm.yaml:/conf/storm.yaml

  frontier:
    image: crawlercommons/url-frontier:latest
    container_name: stormcrawler-frontier
    ports:
      - "7071:7071"
    volumes:
      - ./frontier:/data
    command: ["--port", "7071"]

  runner:
    image: maven:3.9.9-eclipse-temurin-17
    container_name: stormcrawler-runner
    working_dir: /crawldata
    depends_on:
      - nimbus
      - supervisor
      - ui
      - frontier
    volumes:
      - ./crawldata:/crawldata
      - maven-repo:/root/.m2
    environment:
      - MAVEN_OPTS=-Dmaven.repo.local=/root/.m2/repository
    command: tail -f /dev/null

volumes:
  zookeeper-data:
  zookeeper-datalog:
  maven-repo: