version: '3.8'

services:
  scylladb:
    image: scylladb/scylla:latest
    container_name: scylladb-crud
    ports:
      - "9042:9042"
      - "9160:9160"
      - "10000:10000"
    environment:
      - SCYLLA_CLUSTER_NAME=test-cluster
    volumes:
      - scylla_data:/var/lib/scylla
    command: >
      --smp 1 
      --memory 750M 
      --overprovisioned 1 
      --api-address 0.0.0.0
      --listen-address 0.0.0.0
      --rpc-address 0.0.0.0
      --broadcast-address 127.0.0.1
      --broadcast-rpc-address 127.0.0.1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  scylla_data:
    driver: local